/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DomainModel.ChucVu;
import DomainModel.NhanVien;
import Service.NhanVienService;
import Service.ValidateData;
import Service.impl.NhanVienServiceimpl;
import Service.impl.ValidateDataImpl;
import java.awt.Color;
<<<<<<< HEAD
import java.util.UUID;
=======
import java.util.regex.Pattern;
>>>>>>> origin/main
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class Register extends javax.swing.JFrame {

    private ValidateData check = new ValidateDataImpl();
    private NhanVienService nvs = new NhanVienServiceimpl();

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        lbEmail.setText(" ");
        lbName.setText(" ");
        lbPass.setText(" ");
        lbUser.setText(" ");
        lbReset.setText(" ");
        rdoNam.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pfPass = new javax.swing.JPasswordField();
        pfConfirm = new javax.swing.JPasswordField();
        lbName = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbUser = new javax.swing.JLabel();
        lbPass = new javax.swing.JLabel();
        lbReset = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        cbAgree = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 153, 255));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(51, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("REGISTER");

        jLabel2.setFont(new java.awt.Font(".VnArialH", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(180, 180, 160));
        jLabel2.setText("Full Name");

        txtName.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        txtName.setForeground(new java.awt.Color(200, 200, 200));
        txtName.setText("Name...");
        txtName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(241, 241, 241)));
        txtName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNameMouseClicked(evt);
            }
        });
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font(".VnArialH", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(180, 180, 160));
        jLabel3.setText("EMAIL");

<<<<<<< HEAD
        txtEmail.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(200, 200, 200));
        txtEmail.setText("Email...");
        txtEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(241, 241, 241)));
        txtEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEmailMouseClicked(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
=======
        txtNumber.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        txtNumber.setForeground(new java.awt.Color(200, 200, 200));
        txtNumber.setText("Email Address...");
        txtNumber.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(241, 241, 241)));
        txtNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumberActionPerformed(evt);
>>>>>>> origin/main
            }
        });

        jLabel4.setFont(new java.awt.Font(".VnArialH", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(180, 180, 160));
        jLabel4.setText("USername");

        txtUser.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        txtUser.setForeground(new java.awt.Color(200, 200, 200));
        txtUser.setText("UserName...");
        txtUser.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(241, 241, 241)));
<<<<<<< HEAD
        txtUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUserMouseClicked(evt);
            }
        });
        txtUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUserKeyReleased(evt);
=======
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
>>>>>>> origin/main
            }
        });

        jLabel5.setFont(new java.awt.Font(".VnArialH", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(180, 180, 160));
        jLabel5.setText("Password");

        jLabel6.setFont(new java.awt.Font(".VnArialH", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(180, 180, 160));
        jLabel6.setText("repeat password");

        pfPass.setForeground(new java.awt.Color(200, 200, 200));
        pfPass.setText("jPasswordField1");
        pfPass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(241, 241, 241)));
<<<<<<< HEAD
        pfPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pfPassKeyPressed(evt);
=======
        pfPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfPassActionPerformed(evt);
>>>>>>> origin/main
            }
        });

        pfConfirm.setForeground(new java.awt.Color(200, 200, 200));
        pfConfirm.setText("jPasswordField1");
        pfConfirm.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(241, 241, 241)));
<<<<<<< HEAD
        pfConfirm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pfConfirmKeyPressed(evt);
=======
        pfConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfConfirmActionPerformed(evt);
>>>>>>> origin/main
            }
        });

        lbName.setForeground(new java.awt.Color(255, 0, 0));
        lbName.setText("jLabel9");

        lbEmail.setForeground(new java.awt.Color(255, 0, 0));
        lbEmail.setText("jLabel10");

        lbUser.setForeground(new java.awt.Color(255, 0, 0));
        lbUser.setText("jLabel11");

        lbPass.setForeground(new java.awt.Color(255, 0, 0));
        lbPass.setText("jLabel12");

        lbReset.setForeground(new java.awt.Color(255, 0, 0));
        lbReset.setText("jLabel13");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/enter_40px.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        txtLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtLogin.setText("LOGIN");
        txtLogin.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLoginMouseClicked(evt);
            }
        });

        cbAgree.setBackground(new java.awt.Color(255, 255, 255));
        cbAgree.setFont(new java.awt.Font(".VnBahamasBH", 0, 14)); // NOI18N
        cbAgree.setText("I agree to the Terms of User");
        cbAgree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbAgreeMouseClicked(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(85, 52, 165));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ĐĂNG KÍ");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font(".VnAvantH", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(180, 180, 160));
        jLabel8.setText("SEX");

        rdoNam.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdoNam);
        rdoNam.setFont(new java.awt.Font(".VnAvantH", 1, 12)); // NOI18N
        rdoNam.setForeground(new java.awt.Color(180, 180, 160));
        rdoNam.setText("Male");

        rdoNu.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdoNu);
        rdoNu.setFont(new java.awt.Font(".VnAvantH", 1, 12)); // NOI18N
        rdoNu.setForeground(new java.awt.Color(180, 180, 160));
        rdoNu.setText("Female");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(lbName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(pfConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pfPass, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbUser, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(19, 19, 19)))))
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbReset, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbPass, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(186, 186, 186)
                                        .addComponent(rdoNu)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdoNam))
                            .addComponent(cbAgree, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbName))
                .addGap(0, 0, 0)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbEmail))
                .addGap(0, 0, 0)
                .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbUser))
                .addGap(0, 0, 0)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbPass))
                .addGap(0, 0, 0)
                .addComponent(pfPass, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbReset)))
                .addGap(0, 0, 0)
                .addComponent(pfConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdoNam, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(rdoNu)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(17, 17, 17)
                .addComponent(cbAgree)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void txtLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLoginMouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txtLoginMouseClicked

    private void txtNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNameMouseClicked
        if (txtName.getText().equals("Name...")) {
            txtName.setText("");
        }
    }//GEN-LAST:event_txtNameMouseClicked

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        if (check.CheckFullName(txtName.getText()) == false) {
            lbName.setText("Tên không đúng định dạng");
        } else {
            lbName.setText("");
        }
    }//GEN-LAST:event_txtNameKeyReleased

<<<<<<< HEAD
    private void txtEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmailMouseClicked
        if (txtEmail.getText().equals("Email...")) {
            txtEmail.setText("");
        }
    }//GEN-LAST:event_txtEmailMouseClicked

    private void txtUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserMouseClicked
        if (txtUser.getText().equals("UserName...")) {
            txtUser.setText("");
        }
    }//GEN-LAST:event_txtUserMouseClicked

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
;
        if (check.CheckEmail(txtEmail.getText()) == false) {
            lbEmail.setText("Email không đúng định dạng");
        } else {
            lbEmail.setText("");
        }
    }//GEN-LAST:event_txtEmailKeyReleased

    private void txtUserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserKeyReleased
        if (check.CheckUserName(txtUser.getText())) {
            lbUser.setText("");
        } else {
            lbUser.setText("Username không đúng định dạng");
        }
    }//GEN-LAST:event_txtUserKeyReleased

    private void pfPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfPassKeyPressed
        if (check.CheckPass(pfPass.getText()) == false) {
            lbPass.setText("Mật khẩu có độ dài từ 6 - 20");
        } else {
            lbPass.setText("");
        }
    }//GEN-LAST:event_pfPassKeyPressed

    private void pfConfirmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfConfirmKeyPressed
        if (pfConfirm.getText().equals(pfPass.getText())) {
            lbReset.setText("Không khớp với mật khẩu");
        } else {
            lbReset.setText("");
        }
    }//GEN-LAST:event_pfConfirmKeyPressed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if (cbAgree.isSelected() == false) {
            cbAgree.setBorderPainted(true);
            cbAgree.setBorder(BorderFactory.createLineBorder(Color.RED, 2));
        } else if (!"".equals(lbEmail.getText())) {
            JOptionPane.showMessageDialog(this, "Nhập đầy đủ thông tin!");
        } else if (!"".equals(lbName.getText())) {
            JOptionPane.showMessageDialog(this, "Nhập đầy đủ thông tin!");
        } else if (!"".equals(lbPass.getText())) {
            JOptionPane.showMessageDialog(this, "Nhập đầy đủ thông tin!");
        } else if (!"".equals(lbReset.getText())) {
            JOptionPane.showMessageDialog(this, "Nhập đầy đủ thông tin!");
        } else if (!"".equals(lbUser.getText())) {
            JOptionPane.showMessageDialog(this, "Nhập đầy đủ thông tin!");
        } else {
            ChucVu cv = new ChucVu("85db0ad5-dd54-43f1-b3da-2487750c1030", "CV1", "Nhân Viên");
            String maNV = "NV" + nvs.getall().size() + 1;
            String hoTen = txtName.getText();
            String ngaySinh = String.valueOf(java.time.LocalDate.now());
            String gioiTinh = rdoNam.isSelected() == true ? "Nam" : "Nữ";
            String diaChi = null;
            String SDT = null;
            String tenTK = txtUser.getText();
            String matKhau = pfConfirm.getText();
            NhanVien nv = new NhanVien(String.valueOf(UUID.randomUUID()), cv, maNV, hoTen, ngaySinh, gioiTinh, diaChi, SDT, tenTK, matKhau, 1);
            JOptionPane.showMessageDialog(this, nvs.add(nv));
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void cbAgreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbAgreeMouseClicked
        cbAgree.setBorder(javax.swing.BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_cbAgreeMouseClicked
=======
    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
         if (txtName.getText().equals("")) {
            JOptionPane.showMessageDialog(this, " họ và tên không được để trống");
            return;
        }
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumberActionPerformed
        Pattern p = Pattern.compile("^[0-9]{10}$");
        if(p.matcher(txtNumber.getText()).find()){
            JOptionPane.showMessageDialog(this, "số điện thoại đạt");
        }else{
            JOptionPane.showMessageDialog(this, "số điện thoại không được quá 10 số");
            return;
        }
    }//GEN-LAST:event_txtNumberActionPerformed

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        if (txtUser.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "tên khòng được trống");
            return;
        }
    }//GEN-LAST:event_txtUserActionPerformed

    private void pfPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfPassActionPerformed
         if (pfPass.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Mật Khẩu không được trống");
            return;
        }
    }//GEN-LAST:event_pfPassActionPerformed

    private void pfConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfConfirmActionPerformed
         if (pfConfirm.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Mật Khẩu không được trống");
            return;
        }if(pfConfirm != pfPass){
             JOptionPane.showMessageDialog(this, "Mật Khẩu phải trùng");
             return;
        }
    }//GEN-LAST:event_pfConfirmActionPerformed
>>>>>>> origin/main

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbAgree;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbPass;
    private javax.swing.JLabel lbReset;
    private javax.swing.JLabel lbUser;
    private javax.swing.JPasswordField pfConfirm;
    private javax.swing.JPasswordField pfPass;
<<<<<<< HEAD
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JTextField txtEmail;
=======
>>>>>>> origin/main
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNumber;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
